WITH RANKED AS (
    SELECT 
        ID,
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS TILE
    FROM ECOLI_DATA
)
SELECT 
    r.ID,
    CASE 
        WHEN r.TILE = 1 THEN 'CRITICAL'
        WHEN r.TILE = 2 THEN 'HIGH'
        WHEN r.TILE = 3 THEN 'MEDIUM'
        WHEN r.TILE = 4 THEN 'LOW'
    END AS COLONY_NAME
FROM RANKED r
ORDER BY r.ID;
