SELECT h.CAR_ID, ROUND(AVG(DATEDIFF(h.END_DATE,h.START_DATE)+1),1) as AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
GROUP BY h.CAR_ID
HAVING AVG(DATEDIFF(h.END_DATE,h.START_DATE)+1) >= 7
ORDER BY AVERAGE_DURATION DESC, h.CAR_ID DESC;