-- 코드를 입력하세요
SELECT i.NAME, i.DATETIME
FROM ANIMAL_INS i 
# LEFT JOIN ANIMAL_OUTS o ON i.ANIMAL_ID = o.ANIMAL_ID
WHERE i.ANIMAL_ID not in (
    SELECT o.ANIMAL_ID
    FROM ANIMAL_OUTS o
)
ORDER BY i.DATETIME
LIMIT 3;