SELECT
  h.HISTORY_ID,
  CAST(
    c.DAILY_FEE
    * (DATEDIFF(h.END_DATE, h.START_DATE) + 1)
    * (100 - IFNULL(p.DISCOUNT_RATE, 0)) / 100
    AS SIGNED
  ) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
JOIN CAR_RENTAL_COMPANY_CAR c
  ON c.CAR_ID = h.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
  ON p.CAR_TYPE = c.CAR_TYPE
 AND CAST(REPLACE(p.DURATION_TYPE, '일 이상', '') AS UNSIGNED) =
    (
      SELECT MAX(CAST(REPLACE(dp.DURATION_TYPE, '일 이상', '') AS UNSIGNED))
      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN dp
      WHERE dp.CAR_TYPE = c.CAR_TYPE
        AND CAST(REPLACE(dp.DURATION_TYPE, '일 이상', '') AS UNSIGNED)
            <= (DATEDIFF(h.END_DATE, h.START_DATE) + 1)
    )
WHERE c.CAR_TYPE = '트럭'
ORDER BY FEE DESC, h.HISTORY_ID DESC;
