SELECT 
    MONTH(h.START_DATE) AS MONTH, 
    h.CAR_ID, 
    COUNT(*) AS RECORDS
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY h
WHERE 
    YEAR(h.START_DATE) = 2022 
    AND MONTH(h.START_DATE) BETWEEN 8 AND 10
    AND h.CAR_ID IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) BETWEEN 8 AND 10
        GROUP BY CAR_ID
        HAVING COUNT(*) >= 5
    )
GROUP BY 
    MONTH(h.START_DATE), h.CAR_ID
ORDER BY 
    MONTH(h.START_DATE), h.CAR_ID DESC;
