SELECT
  EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR,
  ( 
    -- 연도별 최대 SIZE_OF_COLONY 구하기
    (SELECT MAX(SIZE_OF_COLONY)
     FROM ECOLI_DATA ed2
     WHERE EXTRACT(YEAR FROM ed2.DIFFERENTIATION_DATE) = EXTRACT(YEAR FROM ed1.DIFFERENTIATION_DATE))
    - ed1.SIZE_OF_COLONY
  ) AS YEAR_DEV,
  ed1.ID
FROM
  ECOLI_DATA ed1
ORDER BY
  YEAR ASC,
  YEAR_DEV ASC;