-- 코드를 입력하세요
SELECT distinct h.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
JOIN CAR_RENTAL_COMPANY_CAR c ON c.CAR_ID = h.CAR_ID
WHERE c.CAR_TYPE = '세단' and MONTH(h.START_DATE) = 10
ORDER BY h.CAR_ID DESC;