-- 코드를 작성해주세요
SELECT d.DEPT_ID, d.DEPT_NAME_EN, ROUND(AVG(e.SAL)) as AVG_SAL
FROM HR_EMPLOYEES e
JOIN HR_DEPARTMENT d ON e.DEPT_ID = d.DEPT_ID
GROUP BY d.DEPT_ID, d.DEPT_NAME_EN
ORDER BY AVG(e.SAL) DESC;
