SELECT b.CATEGORY, SUM(ba.SALES) as TOTAL_SALES 
FROM BOOK b 
JOIN BOOK_SALES ba ON b.BOOK_ID = ba.BOOK_ID
WHERE DATE_FORMAT(ba.SALES_DATE,'%Y-%m') = '2022-01'
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY;